/**
 * One-off generator: produces 100 tasteful, visually distinct palettes
 * (light + dark token sets) and writes the static array literal into
 * styles/palettes.ts. Run once with `npm run generate:palettes`;
 * the output file has no runtime dependency on this script afterward.
 */
import fs from "fs";
import path from "path";

type HSL = { h: number; s: number; l: number };

function hslToHex({ h, s, l }: HSL): string {
  s /= 100;
  l /= 100;
  const k = (n: number) => (n + h / 30) % 12;
  const a = s * Math.min(l, 1 - l);
  const f = (n: number) =>
    l - a * Math.max(-1, Math.min(k(n) - 3, Math.min(9 - k(n), 1)));
  const toHex = (x: number) =>
    Math.round(x * 255)
      .toString(16)
      .padStart(2, "0");
  return `#${toHex(f(0))}${toHex(f(8))}${toHex(f(4))}`;
}

const hueNames: [number, string][] = [
  [0, "Rose"],
  [15, "Terracotta"],
  [25, "Amber"],
  [35, "Clay"],
  [45, "Gold"],
  [60, "Citrine"],
  [80, "Olive"],
  [100, "Moss"],
  [120, "Emerald"],
  [140, "Jade"],
  [160, "Teal"],
  [175, "Aqua"],
  [190, "Cyan"],
  [205, "Sky"],
  [215, "Azure"],
  [225, "Cobalt"],
  [235, "Indigo"],
  [250, "Violet"],
  [265, "Iris"],
  [280, "Plum"],
  [295, "Orchid"],
  [310, "Magenta"],
  [325, "Berry"],
  [340, "Ruby"],
  [350, "Crimson"],
];

const toneNames = ["Mist", "Slate", "Dusk", "Haze", "Grove"];

function name(i: number, hueLabel: string): string {
  const tone = toneNames[i % toneNames.length];
  return `${hueLabel} ${tone}`;
}

type PaletteTokens = {
  accent1: string;
  accent2: string;
  surface: string;
  bg: string;
  text: string;
};

type Palette = {
  id: string;
  name: string;
  light: PaletteTokens;
  dark: PaletteTokens;
};

const palettes: Palette[] = [];

// Hand-crafted default palette (index 0)
palettes.push({
  id: "default",
  name: "Refined Slate Teal",
  light: {
    bg: "#f8fafc",
    surface: "#ffffff",
    text: "#1e293b",
    accent1: "#0f766e",
    accent2: "#334155",
  },
  dark: {
    bg: "#0f172a",
    surface: "#1e293b",
    text: "#e2e8f0",
    accent1: "#14b8a6",
    accent2: "#94a3b8",
  },
});

let counter = 0;
outer: for (let hi = 0; hi < hueNames.length; hi++) {
  const [hue, hueLabel] = hueNames[hi];
  for (let vi = 0; vi < toneNames.length; vi++) {
    if (palettes.length >= 100) break outer;
    counter++;
    const secondaryHue = (hue + 40 + vi * 6) % 360;
    const light: PaletteTokens = {
      bg: hslToHex({ h: hue, s: 25 + (vi % 3) * 4, l: 97 }),
      surface: hslToHex({ h: hue, s: 15, l: 100 }),
      text: hslToHex({ h: hue, s: 25, l: 18 }),
      accent1: hslToHex({ h: hue, s: 55 + (vi % 3) * 5, l: 38 - vi }),
      accent2: hslToHex({ h: secondaryHue, s: 30, l: 32 }),
    };
    const dark: PaletteTokens = {
      bg: hslToHex({ h: hue, s: 30, l: 9 }),
      surface: hslToHex({ h: hue, s: 22, l: 15 }),
      text: hslToHex({ h: hue, s: 20, l: 92 }),
      accent1: hslToHex({ h: hue, s: 60, l: 55 + (vi % 2) * 5 }),
      accent2: hslToHex({ h: secondaryHue, s: 25, l: 65 }),
    };
    palettes.push({
      id: `p${counter}`,
      name: name(vi, hueLabel),
      light,
      dark,
    });
  }
}

// Ensure exactly 100
while (palettes.length < 100) {
  const idx = palettes.length;
  palettes.push({
    id: `p${idx}`,
    name: `Neutral Tone ${idx}`,
    light: {
      bg: "#f8f8f8",
      surface: "#ffffff",
      text: "#222222",
      accent1: "#555555",
      accent2: "#888888",
    },
    dark: {
      bg: "#111111",
      surface: "#1c1c1c",
      text: "#eeeeee",
      accent1: "#aaaaaa",
      accent2: "#777777",
    },
  });
}
palettes.length = 100;

const seen = new Set<string>();
for (const p of palettes) {
  let base = p.name;
  let n = base;
  let i = 2;
  while (seen.has(n)) {
    n = `${base} ${i}`;
    i++;
  }
  seen.add(n);
  p.name = n;
}

const fileContent = `// AUTO-GENERATED by scripts/generate-palettes.ts — do not hand-edit.
// 100 named palettes, each with light + dark token sets.
export type PaletteTokens = {
  accent1: string;
  accent2: string;
  surface: string;
  bg: string;
  text: string;
};

export type Palette = {
  id: string;
  name: string;
  light: PaletteTokens;
  dark: PaletteTokens;
};

export const palettes: Palette[] = ${JSON.stringify(palettes, null, 2)};

export const defaultPalette = palettes[0];
`;

const outPath = path.join(__dirname, "..", "styles", "palettes.ts");
fs.writeFileSync(outPath, fileContent, "utf-8");
console.log(`Wrote ${palettes.length} palettes to ${outPath}`);
