// AUTO-GENERATED by scripts/generate-palettes.ts — do not hand-edit.
// 100 named palettes, each with light + dark token sets.
export type PaletteTokens = {
  accent1: string;
  accent2: string;
  surface: string;
  bg: string;
  text: string;
};

export type Palette = {
  id: string;
  name: string;
  light: PaletteTokens;
  dark: PaletteTokens;
};

export const palettes: Palette[] = [
  {
    "id": "default",
    "name": "Refined Slate Teal",
    "light": {
      "bg": "#f8fafc",
      "surface": "#ffffff",
      "text": "#1e293b",
      "accent1": "#0f766e",
      "accent2": "#334155"
    },
    "dark": {
      "bg": "#0f172a",
      "surface": "#1e293b",
      "text": "#e2e8f0",
      "accent1": "#14b8a6",
      "accent2": "#94a3b8"
    }
  },
  {
    "id": "p1",
    "name": "Rose Mist",
    "light": {
      "bg": "#f9f5f5",
      "surface": "#ffffff",
      "text": "#392222",
      "accent1": "#962c2c",
      "accent2": "#6a5a39"
    },
    "dark": {
      "bg": "#1e1010",
      "surface": "#2f1e1e",
      "text": "#efe7e7",
      "accent1": "#d14747",
      "accent2": "#bcad8f"
    }
  },
  {
    "id": "p2",
    "name": "Rose Slate",
    "light": {
      "bg": "#faf5f5",
      "surface": "#ffffff",
      "text": "#392222",
      "accent1": "#972626",
      "accent2": "#6a5f39"
    },
    "dark": {
      "bg": "#1e1010",
      "surface": "#2f1e1e",
      "text": "#efe7e7",
      "accent1": "#d65c5c",
      "accent2": "#bcb28f"
    }
  },
  {
    "id": "p3",
    "name": "Rose Dusk",
    "light": {
      "bg": "#faf5f5",
      "surface": "#ffffff",
      "text": "#392222",
      "accent1": "#972020",
      "accent2": "#6a6439"
    },
    "dark": {
      "bg": "#1e1010",
      "surface": "#2f1e1e",
      "text": "#efe7e7",
      "accent1": "#d14747",
      "accent2": "#bcb68f"
    }
  },
  {
    "id": "p4",
    "name": "Rose Haze",
    "light": {
      "bg": "#f9f5f5",
      "surface": "#ffffff",
      "text": "#392222",
      "accent1": "#8a2828",
      "accent2": "#6a6839"
    },
    "dark": {
      "bg": "#1e1010",
      "surface": "#2f1e1e",
      "text": "#efe7e7",
      "accent1": "#d65c5c",
      "accent2": "#bcbb8f"
    }
  },
  {
    "id": "p5",
    "name": "Rose Grove",
    "light": {
      "bg": "#faf5f5",
      "surface": "#ffffff",
      "text": "#392222",
      "accent1": "#8b2323",
      "accent2": "#676a39"
    },
    "dark": {
      "bg": "#1e1010",
      "surface": "#2f1e1e",
      "text": "#efe7e7",
      "accent1": "#d14747",
      "accent2": "#b9bc8f"
    }
  },
  {
    "id": "p6",
    "name": "Terracotta Mist",
    "light": {
      "bg": "#f9f6f5",
      "surface": "#ffffff",
      "text": "#392822",
      "accent1": "#96462c",
      "accent2": "#6a6639"
    },
    "dark": {
      "bg": "#1e1410",
      "surface": "#2f221e",
      "text": "#efe9e7",
      "accent1": "#d16a47",
      "accent2": "#bcb88f"
    }
  },
  {
    "id": "p7",
    "name": "Terracotta Slate",
    "light": {
      "bg": "#faf6f5",
      "surface": "#ffffff",
      "text": "#392822",
      "accent1": "#974226",
      "accent2": "#696a39"
    },
    "dark": {
      "bg": "#1e1410",
      "surface": "#2f221e",
      "text": "#efe9e7",
      "accent1": "#d67a5c",
      "accent2": "#bbbc8f"
    }
  },
  {
    "id": "p8",
    "name": "Terracotta Dusk",
    "light": {
      "bg": "#faf6f5",
      "surface": "#ffffff",
      "text": "#392822",
      "accent1": "#973e20",
      "accent2": "#646a39"
    },
    "dark": {
      "bg": "#1e1410",
      "surface": "#2f221e",
      "text": "#efe9e7",
      "accent1": "#d16a47",
      "accent2": "#b7bc8f"
    }
  },
  {
    "id": "p9",
    "name": "Terracotta Haze",
    "light": {
      "bg": "#f9f6f5",
      "surface": "#ffffff",
      "text": "#392822",
      "accent1": "#8a4128",
      "accent2": "#5f6a39"
    },
    "dark": {
      "bg": "#1e1410",
      "surface": "#2f221e",
      "text": "#efe9e7",
      "accent1": "#d67a5c",
      "accent2": "#b2bc8f"
    }
  },
  {
    "id": "p10",
    "name": "Terracotta Grove",
    "light": {
      "bg": "#faf6f5",
      "surface": "#ffffff",
      "text": "#392822",
      "accent1": "#8b3d23",
      "accent2": "#5b6a39"
    },
    "dark": {
      "bg": "#1e1410",
      "surface": "#2f221e",
      "text": "#efe9e7",
      "accent1": "#d16a47",
      "accent2": "#aebc8f"
    }
  },
  {
    "id": "p11",
    "name": "Amber Mist",
    "light": {
      "bg": "#f9f7f5",
      "surface": "#ffffff",
      "text": "#392c22",
      "accent1": "#96582c",
      "accent2": "#666a39"
    },
    "dark": {
      "bg": "#1e1610",
      "surface": "#2f251e",
      "text": "#efeae7",
      "accent1": "#d18147",
      "accent2": "#b8bc8f"
    }
  },
  {
    "id": "p12",
    "name": "Amber Slate",
    "light": {
      "bg": "#faf7f5",
      "surface": "#ffffff",
      "text": "#392c22",
      "accent1": "#975526",
      "accent2": "#616a39"
    },
    "dark": {
      "bg": "#1e1610",
      "surface": "#2f251e",
      "text": "#efeae7",
      "accent1": "#d68f5c",
      "accent2": "#b4bc8f"
    }
  },
  {
    "id": "p13",
    "name": "Amber Dusk",
    "light": {
      "bg": "#faf7f5",
      "surface": "#ffffff",
      "text": "#392c22",
      "accent1": "#975220",
      "accent2": "#5c6a39"
    },
    "dark": {
      "bg": "#1e1610",
      "surface": "#2f251e",
      "text": "#efeae7",
      "accent1": "#d18147",
      "accent2": "#afbc8f"
    }
  },
  {
    "id": "p14",
    "name": "Amber Haze",
    "light": {
      "bg": "#f9f7f5",
      "surface": "#ffffff",
      "text": "#392c22",
      "accent1": "#8a5128",
      "accent2": "#576a39"
    },
    "dark": {
      "bg": "#1e1610",
      "surface": "#2f251e",
      "text": "#efeae7",
      "accent1": "#d68f5c",
      "accent2": "#abbc8f"
    }
  },
  {
    "id": "p15",
    "name": "Amber Grove",
    "light": {
      "bg": "#faf7f5",
      "surface": "#ffffff",
      "text": "#392c22",
      "accent1": "#8b4e23",
      "accent2": "#526a39"
    },
    "dark": {
      "bg": "#1e1610",
      "surface": "#2f251e",
      "text": "#efeae7",
      "accent1": "#d18147",
      "accent2": "#a6bc8f"
    }
  },
  {
    "id": "p16",
    "name": "Clay Mist",
    "light": {
      "bg": "#f9f8f5",
      "surface": "#ffffff",
      "text": "#393022",
      "accent1": "#966a2c",
      "accent2": "#5e6a39"
    },
    "dark": {
      "bg": "#1e1810",
      "surface": "#2f281e",
      "text": "#efebe7",
      "accent1": "#d19847",
      "accent2": "#b1bc8f"
    }
  },
  {
    "id": "p17",
    "name": "Clay Slate",
    "light": {
      "bg": "#faf8f5",
      "surface": "#ffffff",
      "text": "#393022",
      "accent1": "#976826",
      "accent2": "#596a39"
    },
    "dark": {
      "bg": "#1e1810",
      "surface": "#2f281e",
      "text": "#efebe7",
      "accent1": "#d6a35c",
      "accent2": "#acbc8f"
    }
  },
  {
    "id": "p18",
    "name": "Clay Dusk",
    "light": {
      "bg": "#faf8f5",
      "surface": "#ffffff",
      "text": "#393022",
      "accent1": "#976620",
      "accent2": "#546a39"
    },
    "dark": {
      "bg": "#1e1810",
      "surface": "#2f281e",
      "text": "#efebe7",
      "accent1": "#d19847",
      "accent2": "#a8bc8f"
    }
  },
  {
    "id": "p19",
    "name": "Clay Haze",
    "light": {
      "bg": "#f9f8f5",
      "surface": "#ffffff",
      "text": "#393022",
      "accent1": "#8a6128",
      "accent2": "#4f6a39"
    },
    "dark": {
      "bg": "#1e1810",
      "surface": "#2f281e",
      "text": "#efebe7",
      "accent1": "#d6a35c",
      "accent2": "#a4bc8f"
    }
  },
  {
    "id": "p20",
    "name": "Clay Grove",
    "light": {
      "bg": "#faf8f5",
      "surface": "#ffffff",
      "text": "#393022",
      "accent1": "#8b5f23",
      "accent2": "#4a6a39"
    },
    "dark": {
      "bg": "#1e1810",
      "surface": "#2f281e",
      "text": "#efebe7",
      "accent1": "#d19847",
      "accent2": "#9fbc8f"
    }
  },
  {
    "id": "p21",
    "name": "Gold Mist",
    "light": {
      "bg": "#f9f8f5",
      "surface": "#ffffff",
      "text": "#393422",
      "accent1": "#967c2c",
      "accent2": "#566a39"
    },
    "dark": {
      "bg": "#1e1a10",
      "surface": "#2f2a1e",
      "text": "#efede7",
      "accent1": "#d1af47",
      "accent2": "#a9bc8f"
    }
  },
  {
    "id": "p22",
    "name": "Gold Slate",
    "light": {
      "bg": "#faf8f5",
      "surface": "#ffffff",
      "text": "#393422",
      "accent1": "#977b26",
      "accent2": "#516a39"
    },
    "dark": {
      "bg": "#1e1a10",
      "surface": "#2f2a1e",
      "text": "#efede7",
      "accent1": "#d6b85c",
      "accent2": "#a5bc8f"
    }
  },
  {
    "id": "p23",
    "name": "Gold Dusk",
    "light": {
      "bg": "#faf9f5",
      "surface": "#ffffff",
      "text": "#393422",
      "accent1": "#977a20",
      "accent2": "#4c6a39"
    },
    "dark": {
      "bg": "#1e1a10",
      "surface": "#2f2a1e",
      "text": "#efede7",
      "accent1": "#d1af47",
      "accent2": "#a1bc8f"
    }
  },
  {
    "id": "p24",
    "name": "Gold Haze",
    "light": {
      "bg": "#f9f8f5",
      "surface": "#ffffff",
      "text": "#393422",
      "accent1": "#8a7228",
      "accent2": "#476a39"
    },
    "dark": {
      "bg": "#1e1a10",
      "surface": "#2f2a1e",
      "text": "#efede7",
      "accent1": "#d6b85c",
      "accent2": "#9cbc8f"
    }
  },
  {
    "id": "p25",
    "name": "Gold Grove",
    "light": {
      "bg": "#faf8f5",
      "surface": "#ffffff",
      "text": "#393422",
      "accent1": "#8b7123",
      "accent2": "#426a39"
    },
    "dark": {
      "bg": "#1e1a10",
      "surface": "#2f2a1e",
      "text": "#efede7",
      "accent1": "#d1af47",
      "accent2": "#98bc8f"
    }
  },
  {
    "id": "p26",
    "name": "Citrine Mist",
    "light": {
      "bg": "#f9f9f5",
      "surface": "#ffffff",
      "text": "#393922",
      "accent1": "#96962c",
      "accent2": "#496a39"
    },
    "dark": {
      "bg": "#1e1e10",
      "surface": "#2f2f1e",
      "text": "#efefe7",
      "accent1": "#d1d147",
      "accent2": "#9ebc8f"
    }
  },
  {
    "id": "p27",
    "name": "Citrine Slate",
    "light": {
      "bg": "#fafaf5",
      "surface": "#ffffff",
      "text": "#393922",
      "accent1": "#979726",
      "accent2": "#456a39"
    },
    "dark": {
      "bg": "#1e1e10",
      "surface": "#2f2f1e",
      "text": "#efefe7",
      "accent1": "#d6d65c",
      "accent2": "#9abc8f"
    }
  },
  {
    "id": "p28",
    "name": "Citrine Dusk",
    "light": {
      "bg": "#fafaf5",
      "surface": "#ffffff",
      "text": "#393922",
      "accent1": "#979720",
      "accent2": "#406a39"
    },
    "dark": {
      "bg": "#1e1e10",
      "surface": "#2f2f1e",
      "text": "#efefe7",
      "accent1": "#d1d147",
      "accent2": "#95bc8f"
    }
  },
  {
    "id": "p29",
    "name": "Citrine Haze",
    "light": {
      "bg": "#f9f9f5",
      "surface": "#ffffff",
      "text": "#393922",
      "accent1": "#8a8a28",
      "accent2": "#3b6a39"
    },
    "dark": {
      "bg": "#1e1e10",
      "surface": "#2f2f1e",
      "text": "#efefe7",
      "accent1": "#d6d65c",
      "accent2": "#91bc8f"
    }
  },
  {
    "id": "p30",
    "name": "Citrine Grove",
    "light": {
      "bg": "#fafaf5",
      "surface": "#ffffff",
      "text": "#393922",
      "accent1": "#8b8b23",
      "accent2": "#396a3c"
    },
    "dark": {
      "bg": "#1e1e10",
      "surface": "#2f2f1e",
      "text": "#efefe7",
      "accent1": "#d1d147",
      "accent2": "#8fbc92"
    }
  },
  {
    "id": "p31",
    "name": "Olive Mist",
    "light": {
      "bg": "#f8f9f5",
      "surface": "#ffffff",
      "text": "#323922",
      "accent1": "#73962c",
      "accent2": "#396a39"
    },
    "dark": {
      "bg": "#191e10",
      "surface": "#292f1e",
      "text": "#ecefe7",
      "accent1": "#a3d147",
      "accent2": "#8fbc8f"
    }
  },
  {
    "id": "p32",
    "name": "Olive Slate",
    "light": {
      "bg": "#f8faf5",
      "surface": "#ffffff",
      "text": "#323922",
      "accent1": "#719726",
      "accent2": "#396a3e"
    },
    "dark": {
      "bg": "#191e10",
      "surface": "#292f1e",
      "text": "#ecefe7",
      "accent1": "#add65c",
      "accent2": "#8fbc94"
    }
  },
  {
    "id": "p33",
    "name": "Olive Dusk",
    "light": {
      "bg": "#f8faf5",
      "surface": "#ffffff",
      "text": "#323922",
      "accent1": "#709720",
      "accent2": "#396a43"
    },
    "dark": {
      "bg": "#191e10",
      "surface": "#292f1e",
      "text": "#ecefe7",
      "accent1": "#a3d147",
      "accent2": "#8fbc98"
    }
  },
  {
    "id": "p34",
    "name": "Olive Haze",
    "light": {
      "bg": "#f8f9f5",
      "surface": "#ffffff",
      "text": "#323922",
      "accent1": "#6a8a28",
      "accent2": "#396a48"
    },
    "dark": {
      "bg": "#191e10",
      "surface": "#292f1e",
      "text": "#ecefe7",
      "accent1": "#add65c",
      "accent2": "#8fbc9d"
    }
  },
  {
    "id": "p35",
    "name": "Olive Grove",
    "light": {
      "bg": "#f8faf5",
      "surface": "#ffffff",
      "text": "#323922",
      "accent1": "#688b23",
      "accent2": "#396a4d"
    },
    "dark": {
      "bg": "#191e10",
      "surface": "#292f1e",
      "text": "#ecefe7",
      "accent1": "#a3d147",
      "accent2": "#8fbca1"
    }
  },
  {
    "id": "p36",
    "name": "Moss Mist",
    "light": {
      "bg": "#f7f9f5",
      "surface": "#ffffff",
      "text": "#2a3922",
      "accent1": "#4f962c",
      "accent2": "#396a49"
    },
    "dark": {
      "bg": "#151e10",
      "surface": "#232f1e",
      "text": "#e9efe7",
      "accent1": "#75d147",
      "accent2": "#8fbc9e"
    }
  },
  {
    "id": "p37",
    "name": "Moss Slate",
    "light": {
      "bg": "#f7faf5",
      "surface": "#ffffff",
      "text": "#2a3922",
      "accent1": "#4b9726",
      "accent2": "#396a4e"
    },
    "dark": {
      "bg": "#151e10",
      "surface": "#232f1e",
      "text": "#e9efe7",
      "accent1": "#85d65c",
      "accent2": "#8fbca3"
    }
  },
  {
    "id": "p38",
    "name": "Moss Dusk",
    "light": {
      "bg": "#f7faf5",
      "surface": "#ffffff",
      "text": "#2a3922",
      "accent1": "#489720",
      "accent2": "#396a53"
    },
    "dark": {
      "bg": "#151e10",
      "surface": "#232f1e",
      "text": "#e9efe7",
      "accent1": "#75d147",
      "accent2": "#8fbca7"
    }
  },
  {
    "id": "p39",
    "name": "Moss Haze",
    "light": {
      "bg": "#f7f9f5",
      "surface": "#ffffff",
      "text": "#2a3922",
      "accent1": "#498a28",
      "accent2": "#396a58"
    },
    "dark": {
      "bg": "#151e10",
      "surface": "#232f1e",
      "text": "#e9efe7",
      "accent1": "#85d65c",
      "accent2": "#8fbcac"
    }
  },
  {
    "id": "p40",
    "name": "Moss Grove",
    "light": {
      "bg": "#f7faf5",
      "surface": "#ffffff",
      "text": "#2a3922",
      "accent1": "#458b23",
      "accent2": "#396a5d"
    },
    "dark": {
      "bg": "#151e10",
      "surface": "#232f1e",
      "text": "#e9efe7",
      "accent1": "#75d147",
      "accent2": "#8fbcb0"
    }
  },
  {
    "id": "p41",
    "name": "Emerald Mist",
    "light": {
      "bg": "#f5f9f5",
      "surface": "#ffffff",
      "text": "#223922",
      "accent1": "#2c962c",
      "accent2": "#396a5a"
    },
    "dark": {
      "bg": "#101e10",
      "surface": "#1e2f1e",
      "text": "#e7efe7",
      "accent1": "#47d147",
      "accent2": "#8fbcad"
    }
  },
  {
    "id": "p42",
    "name": "Emerald Slate",
    "light": {
      "bg": "#f5faf5",
      "surface": "#ffffff",
      "text": "#223922",
      "accent1": "#269726",
      "accent2": "#396a5f"
    },
    "dark": {
      "bg": "#101e10",
      "surface": "#1e2f1e",
      "text": "#e7efe7",
      "accent1": "#5cd65c",
      "accent2": "#8fbcb2"
    }
  },
  {
    "id": "p43",
    "name": "Emerald Dusk",
    "light": {
      "bg": "#f5faf5",
      "surface": "#ffffff",
      "text": "#223922",
      "accent1": "#209720",
      "accent2": "#396a64"
    },
    "dark": {
      "bg": "#101e10",
      "surface": "#1e2f1e",
      "text": "#e7efe7",
      "accent1": "#47d147",
      "accent2": "#8fbcb6"
    }
  },
  {
    "id": "p44",
    "name": "Emerald Haze",
    "light": {
      "bg": "#f5f9f5",
      "surface": "#ffffff",
      "text": "#223922",
      "accent1": "#288a28",
      "accent2": "#396a68"
    },
    "dark": {
      "bg": "#101e10",
      "surface": "#1e2f1e",
      "text": "#e7efe7",
      "accent1": "#5cd65c",
      "accent2": "#8fbcbb"
    }
  },
  {
    "id": "p45",
    "name": "Emerald Grove",
    "light": {
      "bg": "#f5faf5",
      "surface": "#ffffff",
      "text": "#223922",
      "accent1": "#238b23",
      "accent2": "#39676a"
    },
    "dark": {
      "bg": "#101e10",
      "surface": "#1e2f1e",
      "text": "#e7efe7",
      "accent1": "#47d147",
      "accent2": "#8fb9bc"
    }
  },
  {
    "id": "p46",
    "name": "Jade Mist",
    "light": {
      "bg": "#f5f9f7",
      "surface": "#ffffff",
      "text": "#22392a",
      "accent1": "#2c964f",
      "accent2": "#396a6a"
    },
    "dark": {
      "bg": "#101e15",
      "surface": "#1e2f23",
      "text": "#e7efe9",
      "accent1": "#47d175",
      "accent2": "#8fbcbc"
    }
  },
  {
    "id": "p47",
    "name": "Jade Slate",
    "light": {
      "bg": "#f5faf7",
      "surface": "#ffffff",
      "text": "#22392a",
      "accent1": "#26974b",
      "accent2": "#39656a"
    },
    "dark": {
      "bg": "#101e15",
      "surface": "#1e2f23",
      "text": "#e7efe9",
      "accent1": "#5cd685",
      "accent2": "#8fb8bc"
    }
  },
  {
    "id": "p48",
    "name": "Jade Dusk",
    "light": {
      "bg": "#f5faf7",
      "surface": "#ffffff",
      "text": "#22392a",
      "accent1": "#209748",
      "accent2": "#39606a"
    },
    "dark": {
      "bg": "#101e15",
      "surface": "#1e2f23",
      "text": "#e7efe9",
      "accent1": "#47d175",
      "accent2": "#8fb3bc"
    }
  },
  {
    "id": "p49",
    "name": "Jade Haze",
    "light": {
      "bg": "#f5f9f7",
      "surface": "#ffffff",
      "text": "#22392a",
      "accent1": "#288a49",
      "accent2": "#395b6a"
    },
    "dark": {
      "bg": "#101e15",
      "surface": "#1e2f23",
      "text": "#e7efe9",
      "accent1": "#5cd685",
      "accent2": "#8fafbc"
    }
  },
  {
    "id": "p50",
    "name": "Jade Grove",
    "light": {
      "bg": "#f5faf7",
      "surface": "#ffffff",
      "text": "#22392a",
      "accent1": "#238b45",
      "accent2": "#39566a"
    },
    "dark": {
      "bg": "#101e15",
      "surface": "#1e2f23",
      "text": "#e7efe9",
      "accent1": "#47d175",
      "accent2": "#8faabc"
    }
  },
  {
    "id": "p51",
    "name": "Teal Mist",
    "light": {
      "bg": "#f5f9f8",
      "surface": "#ffffff",
      "text": "#223932",
      "accent1": "#2c9673",
      "accent2": "#395a6a"
    },
    "dark": {
      "bg": "#101e19",
      "surface": "#1e2f29",
      "text": "#e7efec",
      "accent1": "#47d1a3",
      "accent2": "#8fadbc"
    }
  },
  {
    "id": "p52",
    "name": "Teal Slate",
    "light": {
      "bg": "#f5faf8",
      "surface": "#ffffff",
      "text": "#223932",
      "accent1": "#269771",
      "accent2": "#39556a"
    },
    "dark": {
      "bg": "#101e19",
      "surface": "#1e2f29",
      "text": "#e7efec",
      "accent1": "#5cd6ad",
      "accent2": "#8fa9bc"
    }
  },
  {
    "id": "p53",
    "name": "Teal Dusk",
    "light": {
      "bg": "#f5faf8",
      "surface": "#ffffff",
      "text": "#223932",
      "accent1": "#209770",
      "accent2": "#39506a"
    },
    "dark": {
      "bg": "#101e19",
      "surface": "#1e2f29",
      "text": "#e7efec",
      "accent1": "#47d1a3",
      "accent2": "#8fa4bc"
    }
  },
  {
    "id": "p54",
    "name": "Teal Haze",
    "light": {
      "bg": "#f5f9f8",
      "surface": "#ffffff",
      "text": "#223932",
      "accent1": "#288a6a",
      "accent2": "#394b6a"
    },
    "dark": {
      "bg": "#101e19",
      "surface": "#1e2f29",
      "text": "#e7efec",
      "accent1": "#5cd6ad",
      "accent2": "#8fa0bc"
    }
  },
  {
    "id": "p55",
    "name": "Teal Grove",
    "light": {
      "bg": "#f5faf8",
      "surface": "#ffffff",
      "text": "#223932",
      "accent1": "#238b68",
      "accent2": "#39466a"
    },
    "dark": {
      "bg": "#101e19",
      "surface": "#1e2f29",
      "text": "#e7efec",
      "accent1": "#47d1a3",
      "accent2": "#8f9bbc"
    }
  },
  {
    "id": "p56",
    "name": "Aqua Mist",
    "light": {
      "bg": "#f5f9f9",
      "surface": "#ffffff",
      "text": "#223937",
      "accent1": "#2c968d",
      "accent2": "#394e6a"
    },
    "dark": {
      "bg": "#101e1d",
      "surface": "#1e2f2d",
      "text": "#e7efee",
      "accent1": "#47d1c6",
      "accent2": "#8fa2bc"
    }
  },
  {
    "id": "p57",
    "name": "Aqua Slate",
    "light": {
      "bg": "#f5faf9",
      "surface": "#ffffff",
      "text": "#223937",
      "accent1": "#26978e",
      "accent2": "#39496a"
    },
    "dark": {
      "bg": "#101e1d",
      "surface": "#1e2f2d",
      "text": "#e7efee",
      "accent1": "#5cd6cc",
      "accent2": "#8f9ebc"
    }
  },
  {
    "id": "p58",
    "name": "Aqua Dusk",
    "light": {
      "bg": "#f5faf9",
      "surface": "#ffffff",
      "text": "#223937",
      "accent1": "#20978e",
      "accent2": "#39446a"
    },
    "dark": {
      "bg": "#101e1d",
      "surface": "#1e2f2d",
      "text": "#e7efee",
      "accent1": "#47d1c6",
      "accent2": "#8f99bc"
    }
  },
  {
    "id": "p59",
    "name": "Aqua Haze",
    "light": {
      "bg": "#f5f9f9",
      "surface": "#ffffff",
      "text": "#223937",
      "accent1": "#288a82",
      "accent2": "#393f6a"
    },
    "dark": {
      "bg": "#101e1d",
      "surface": "#1e2f2d",
      "text": "#e7efee",
      "accent1": "#5cd6cc",
      "accent2": "#8f95bc"
    }
  },
  {
    "id": "p60",
    "name": "Aqua Grove",
    "light": {
      "bg": "#f5faf9",
      "surface": "#ffffff",
      "text": "#223937",
      "accent1": "#238b82",
      "accent2": "#393a6a"
    },
    "dark": {
      "bg": "#101e1d",
      "surface": "#1e2f2d",
      "text": "#e7efee",
      "accent1": "#47d1c6",
      "accent2": "#8f90bc"
    }
  },
  {
    "id": "p61",
    "name": "Cyan Mist",
    "light": {
      "bg": "#f5f9f9",
      "surface": "#ffffff",
      "text": "#223639",
      "accent1": "#2c8496",
      "accent2": "#39416a"
    },
    "dark": {
      "bg": "#101c1e",
      "surface": "#1e2c2f",
      "text": "#e7edef",
      "accent1": "#47bad1",
      "accent2": "#8f97bc"
    }
  },
  {
    "id": "p62",
    "name": "Cyan Slate",
    "light": {
      "bg": "#f5f9fa",
      "surface": "#ffffff",
      "text": "#223639",
      "accent1": "#268497",
      "accent2": "#393c6a"
    },
    "dark": {
      "bg": "#101c1e",
      "surface": "#1e2c2f",
      "text": "#e7edef",
      "accent1": "#5cc2d6",
      "accent2": "#8f92bc"
    }
  },
  {
    "id": "p63",
    "name": "Cyan Dusk",
    "light": {
      "bg": "#f5f9fa",
      "surface": "#ffffff",
      "text": "#223639",
      "accent1": "#208497",
      "accent2": "#3b396a"
    },
    "dark": {
      "bg": "#101c1e",
      "surface": "#1e2c2f",
      "text": "#e7edef",
      "accent1": "#47bad1",
      "accent2": "#918fbc"
    }
  },
  {
    "id": "p64",
    "name": "Cyan Haze",
    "light": {
      "bg": "#f5f9f9",
      "surface": "#ffffff",
      "text": "#223639",
      "accent1": "#287a8a",
      "accent2": "#40396a"
    },
    "dark": {
      "bg": "#101c1e",
      "surface": "#1e2c2f",
      "text": "#e7edef",
      "accent1": "#5cc2d6",
      "accent2": "#958fbc"
    }
  },
  {
    "id": "p65",
    "name": "Cyan Grove",
    "light": {
      "bg": "#f5f9fa",
      "surface": "#ffffff",
      "text": "#223639",
      "accent1": "#23798b",
      "accent2": "#45396a"
    },
    "dark": {
      "bg": "#101c1e",
      "surface": "#1e2c2f",
      "text": "#e7edef",
      "accent1": "#47bad1",
      "accent2": "#9a8fbc"
    }
  },
  {
    "id": "p66",
    "name": "Sky Mist",
    "light": {
      "bg": "#f5f8f9",
      "surface": "#ffffff",
      "text": "#223039",
      "accent1": "#2c6a96",
      "accent2": "#3d396a"
    },
    "dark": {
      "bg": "#10181e",
      "surface": "#1e282f",
      "text": "#e7ebef",
      "accent1": "#4798d1",
      "accent2": "#938fbc"
    }
  },
  {
    "id": "p67",
    "name": "Sky Slate",
    "light": {
      "bg": "#f5f8fa",
      "surface": "#ffffff",
      "text": "#223039",
      "accent1": "#266897",
      "accent2": "#42396a"
    },
    "dark": {
      "bg": "#10181e",
      "surface": "#1e282f",
      "text": "#e7ebef",
      "accent1": "#5ca3d6",
      "accent2": "#988fbc"
    }
  },
  {
    "id": "p68",
    "name": "Sky Dusk",
    "light": {
      "bg": "#f5f8fa",
      "surface": "#ffffff",
      "text": "#223039",
      "accent1": "#206697",
      "accent2": "#47396a"
    },
    "dark": {
      "bg": "#10181e",
      "surface": "#1e282f",
      "text": "#e7ebef",
      "accent1": "#4798d1",
      "accent2": "#9c8fbc"
    }
  },
  {
    "id": "p69",
    "name": "Sky Haze",
    "light": {
      "bg": "#f5f8f9",
      "surface": "#ffffff",
      "text": "#223039",
      "accent1": "#28618a",
      "accent2": "#4c396a"
    },
    "dark": {
      "bg": "#10181e",
      "surface": "#1e282f",
      "text": "#e7ebef",
      "accent1": "#5ca3d6",
      "accent2": "#a18fbc"
    }
  },
  {
    "id": "p70",
    "name": "Sky Grove",
    "light": {
      "bg": "#f5f8fa",
      "surface": "#ffffff",
      "text": "#223039",
      "accent1": "#235f8b",
      "accent2": "#51396a"
    },
    "dark": {
      "bg": "#10181e",
      "surface": "#1e282f",
      "text": "#e7ebef",
      "accent1": "#4798d1",
      "accent2": "#a58fbc"
    }
  },
  {
    "id": "p71",
    "name": "Azure Mist",
    "light": {
      "bg": "#f5f7f9",
      "surface": "#ffffff",
      "text": "#222c39",
      "accent1": "#2c5896",
      "accent2": "#45396a"
    },
    "dark": {
      "bg": "#10161e",
      "surface": "#1e252f",
      "text": "#e7eaef",
      "accent1": "#4781d1",
      "accent2": "#9b8fbc"
    }
  },
  {
    "id": "p72",
    "name": "Azure Slate",
    "light": {
      "bg": "#f5f7fa",
      "surface": "#ffffff",
      "text": "#222c39",
      "accent1": "#265597",
      "accent2": "#4a396a"
    },
    "dark": {
      "bg": "#10161e",
      "surface": "#1e252f",
      "text": "#e7eaef",
      "accent1": "#5c8fd6",
      "accent2": "#9f8fbc"
    }
  },
  {
    "id": "p73",
    "name": "Azure Dusk",
    "light": {
      "bg": "#f5f7fa",
      "surface": "#ffffff",
      "text": "#222c39",
      "accent1": "#205297",
      "accent2": "#4f396a"
    },
    "dark": {
      "bg": "#10161e",
      "surface": "#1e252f",
      "text": "#e7eaef",
      "accent1": "#4781d1",
      "accent2": "#a48fbc"
    }
  },
  {
    "id": "p74",
    "name": "Azure Haze",
    "light": {
      "bg": "#f5f7f9",
      "surface": "#ffffff",
      "text": "#222c39",
      "accent1": "#28518a",
      "accent2": "#54396a"
    },
    "dark": {
      "bg": "#10161e",
      "surface": "#1e252f",
      "text": "#e7eaef",
      "accent1": "#5c8fd6",
      "accent2": "#a88fbc"
    }
  },
  {
    "id": "p75",
    "name": "Azure Grove",
    "light": {
      "bg": "#f5f7fa",
      "surface": "#ffffff",
      "text": "#222c39",
      "accent1": "#234e8b",
      "accent2": "#59396a"
    },
    "dark": {
      "bg": "#10161e",
      "surface": "#1e252f",
      "text": "#e7eaef",
      "accent1": "#4781d1",
      "accent2": "#ac8fbc"
    }
  },
  {
    "id": "p76",
    "name": "Cobalt Mist",
    "light": {
      "bg": "#f5f6f9",
      "surface": "#ffffff",
      "text": "#222839",
      "accent1": "#2c4696",
      "accent2": "#4e396a"
    },
    "dark": {
      "bg": "#10141e",
      "surface": "#1e222f",
      "text": "#e7e9ef",
      "accent1": "#476ad1",
      "accent2": "#a28fbc"
    }
  },
  {
    "id": "p77",
    "name": "Cobalt Slate",
    "light": {
      "bg": "#f5f6fa",
      "surface": "#ffffff",
      "text": "#222839",
      "accent1": "#264297",
      "accent2": "#52396a"
    },
    "dark": {
      "bg": "#10141e",
      "surface": "#1e222f",
      "text": "#e7e9ef",
      "accent1": "#5c7ad6",
      "accent2": "#a68fbc"
    }
  },
  {
    "id": "p78",
    "name": "Cobalt Dusk",
    "light": {
      "bg": "#f5f6fa",
      "surface": "#ffffff",
      "text": "#222839",
      "accent1": "#203e97",
      "accent2": "#57396a"
    },
    "dark": {
      "bg": "#10141e",
      "surface": "#1e222f",
      "text": "#e7e9ef",
      "accent1": "#476ad1",
      "accent2": "#ab8fbc"
    }
  },
  {
    "id": "p79",
    "name": "Cobalt Haze",
    "light": {
      "bg": "#f5f6f9",
      "surface": "#ffffff",
      "text": "#222839",
      "accent1": "#28418a",
      "accent2": "#5c396a"
    },
    "dark": {
      "bg": "#10141e",
      "surface": "#1e222f",
      "text": "#e7e9ef",
      "accent1": "#5c7ad6",
      "accent2": "#af8fbc"
    }
  },
  {
    "id": "p80",
    "name": "Cobalt Grove",
    "light": {
      "bg": "#f5f6fa",
      "surface": "#ffffff",
      "text": "#222839",
      "accent1": "#233d8b",
      "accent2": "#61396a"
    },
    "dark": {
      "bg": "#10141e",
      "surface": "#1e222f",
      "text": "#e7e9ef",
      "accent1": "#476ad1",
      "accent2": "#b48fbc"
    }
  },
  {
    "id": "p81",
    "name": "Indigo Mist",
    "light": {
      "bg": "#f5f6f9",
      "surface": "#ffffff",
      "text": "#222439",
      "accent1": "#2c3496",
      "accent2": "#56396a"
    },
    "dark": {
      "bg": "#10111e",
      "surface": "#1e1f2f",
      "text": "#e7e7ef",
      "accent1": "#4753d1",
      "accent2": "#a98fbc"
    }
  },
  {
    "id": "p82",
    "name": "Indigo Slate",
    "light": {
      "bg": "#f5f6fa",
      "surface": "#ffffff",
      "text": "#222439",
      "accent1": "#262f97",
      "accent2": "#5b396a"
    },
    "dark": {
      "bg": "#10111e",
      "surface": "#1e1f2f",
      "text": "#e7e7ef",
      "accent1": "#5c66d6",
      "accent2": "#ae8fbc"
    }
  },
  {
    "id": "p83",
    "name": "Indigo Dusk",
    "light": {
      "bg": "#f5f5fa",
      "surface": "#ffffff",
      "text": "#222439",
      "accent1": "#202a97",
      "accent2": "#5f396a"
    },
    "dark": {
      "bg": "#10111e",
      "surface": "#1e1f2f",
      "text": "#e7e7ef",
      "accent1": "#4753d1",
      "accent2": "#b28fbc"
    }
  },
  {
    "id": "p84",
    "name": "Indigo Haze",
    "light": {
      "bg": "#f5f6f9",
      "surface": "#ffffff",
      "text": "#222439",
      "accent1": "#28308a",
      "accent2": "#64396a"
    },
    "dark": {
      "bg": "#10111e",
      "surface": "#1e1f2f",
      "text": "#e7e7ef",
      "accent1": "#5c66d6",
      "accent2": "#b78fbc"
    }
  },
  {
    "id": "p85",
    "name": "Indigo Grove",
    "light": {
      "bg": "#f5f6fa",
      "surface": "#ffffff",
      "text": "#222439",
      "accent1": "#232b8b",
      "accent2": "#69396a"
    },
    "dark": {
      "bg": "#10111e",
      "surface": "#1e1f2f",
      "text": "#e7e7ef",
      "accent1": "#4753d1",
      "accent2": "#bb8fbc"
    }
  },
  {
    "id": "p86",
    "name": "Violet Mist",
    "light": {
      "bg": "#f6f5f9",
      "surface": "#ffffff",
      "text": "#262239",
      "accent1": "#3d2c96",
      "accent2": "#62396a"
    },
    "dark": {
      "bg": "#12101e",
      "surface": "#211e2f",
      "text": "#e8e7ef",
      "accent1": "#5e47d1",
      "accent2": "#b58fbc"
    }
  },
  {
    "id": "p87",
    "name": "Violet Slate",
    "light": {
      "bg": "#f6f5fa",
      "surface": "#ffffff",
      "text": "#262239",
      "accent1": "#392697",
      "accent2": "#67396a"
    },
    "dark": {
      "bg": "#12101e",
      "surface": "#211e2f",
      "text": "#e8e7ef",
      "accent1": "#705cd6",
      "accent2": "#b98fbc"
    }
  },
  {
    "id": "p88",
    "name": "Violet Dusk",
    "light": {
      "bg": "#f6f5fa",
      "surface": "#ffffff",
      "text": "#262239",
      "accent1": "#342097",
      "accent2": "#6a3968"
    },
    "dark": {
      "bg": "#12101e",
      "surface": "#211e2f",
      "text": "#e8e7ef",
      "accent1": "#5e47d1",
      "accent2": "#bc8fbb"
    }
  },
  {
    "id": "p89",
    "name": "Violet Haze",
    "light": {
      "bg": "#f6f5f9",
      "surface": "#ffffff",
      "text": "#262239",
      "accent1": "#39288a",
      "accent2": "#6a3964"
    },
    "dark": {
      "bg": "#12101e",
      "surface": "#211e2f",
      "text": "#e8e7ef",
      "accent1": "#705cd6",
      "accent2": "#bc8fb6"
    }
  },
  {
    "id": "p90",
    "name": "Violet Grove",
    "light": {
      "bg": "#f6f5fa",
      "surface": "#ffffff",
      "text": "#262239",
      "accent1": "#34238b",
      "accent2": "#6a395f"
    },
    "dark": {
      "bg": "#12101e",
      "surface": "#211e2f",
      "text": "#e8e7ef",
      "accent1": "#5e47d1",
      "accent2": "#bc8fb2"
    }
  },
  {
    "id": "p91",
    "name": "Iris Mist",
    "light": {
      "bg": "#f7f5f9",
      "surface": "#ffffff",
      "text": "#2c2239",
      "accent1": "#582c96",
      "accent2": "#6a3966"
    },
    "dark": {
      "bg": "#16101e",
      "surface": "#251e2f",
      "text": "#eae7ef",
      "accent1": "#8147d1",
      "accent2": "#bc8fb8"
    }
  },
  {
    "id": "p92",
    "name": "Iris Slate",
    "light": {
      "bg": "#f7f5fa",
      "surface": "#ffffff",
      "text": "#2c2239",
      "accent1": "#552697",
      "accent2": "#6a3961"
    },
    "dark": {
      "bg": "#16101e",
      "surface": "#251e2f",
      "text": "#eae7ef",
      "accent1": "#8f5cd6",
      "accent2": "#bc8fb4"
    }
  },
  {
    "id": "p93",
    "name": "Iris Dusk",
    "light": {
      "bg": "#f7f5fa",
      "surface": "#ffffff",
      "text": "#2c2239",
      "accent1": "#522097",
      "accent2": "#6a395c"
    },
    "dark": {
      "bg": "#16101e",
      "surface": "#251e2f",
      "text": "#eae7ef",
      "accent1": "#8147d1",
      "accent2": "#bc8faf"
    }
  },
  {
    "id": "p94",
    "name": "Iris Haze",
    "light": {
      "bg": "#f7f5f9",
      "surface": "#ffffff",
      "text": "#2c2239",
      "accent1": "#51288a",
      "accent2": "#6a3957"
    },
    "dark": {
      "bg": "#16101e",
      "surface": "#251e2f",
      "text": "#eae7ef",
      "accent1": "#8f5cd6",
      "accent2": "#bc8fab"
    }
  },
  {
    "id": "p95",
    "name": "Iris Grove",
    "light": {
      "bg": "#f7f5fa",
      "surface": "#ffffff",
      "text": "#2c2239",
      "accent1": "#4e238b",
      "accent2": "#6a3952"
    },
    "dark": {
      "bg": "#16101e",
      "surface": "#251e2f",
      "text": "#eae7ef",
      "accent1": "#8147d1",
      "accent2": "#bc8fa6"
    }
  },
  {
    "id": "p96",
    "name": "Plum Mist",
    "light": {
      "bg": "#f8f5f9",
      "surface": "#ffffff",
      "text": "#322239",
      "accent1": "#732c96",
      "accent2": "#6a395a"
    },
    "dark": {
      "bg": "#19101e",
      "surface": "#291e2f",
      "text": "#ece7ef",
      "accent1": "#a347d1",
      "accent2": "#bc8fad"
    }
  },
  {
    "id": "p97",
    "name": "Plum Slate",
    "light": {
      "bg": "#f8f5fa",
      "surface": "#ffffff",
      "text": "#322239",
      "accent1": "#712697",
      "accent2": "#6a3955"
    },
    "dark": {
      "bg": "#19101e",
      "surface": "#291e2f",
      "text": "#ece7ef",
      "accent1": "#ad5cd6",
      "accent2": "#bc8fa9"
    }
  },
  {
    "id": "p98",
    "name": "Plum Dusk",
    "light": {
      "bg": "#f8f5fa",
      "surface": "#ffffff",
      "text": "#322239",
      "accent1": "#702097",
      "accent2": "#6a3950"
    },
    "dark": {
      "bg": "#19101e",
      "surface": "#291e2f",
      "text": "#ece7ef",
      "accent1": "#a347d1",
      "accent2": "#bc8fa4"
    }
  },
  {
    "id": "p99",
    "name": "Plum Haze",
    "light": {
      "bg": "#f8f5f9",
      "surface": "#ffffff",
      "text": "#322239",
      "accent1": "#6a288a",
      "accent2": "#6a394b"
    },
    "dark": {
      "bg": "#19101e",
      "surface": "#291e2f",
      "text": "#ece7ef",
      "accent1": "#ad5cd6",
      "accent2": "#bc8fa0"
    }
  }
];

export const defaultPalette = palettes[0];
